### PR TITLE
fix type issue

### PR DESCRIPTION
**Pull request by cdaniluk**

### CODE REVIEW

**Review by sblack4 — APPROVED** [review]
what is going on

**Comment by smiller171** [comment]
I'm confused as well. This says no changes?

**Review by sblack4 — CHANGES_REQUESTED** [review]
Alphabetize your variables

**Comment by cdaniluk** [comment]
I think this should probably be a draft PR.. or closed. I'm pretty sure I tested this and it didn't end up working. I'm pretty sure the source module is still broken.

**Comment by sblack4** [comment]
Are there supposed to be 0 changes? Here's a pertinent quote. 

> Insanity is doing the same thing over and over again and expecting different results

**Comment by cdaniluk** [comment]
> Are there supposed to be 0 changes? Here's a pertinent quote.
> 
> > Insanity is doing the same thing over and over again and expecting different results

If you look at the commits, it appears that this was inadvertently merged outside of the PR. The module is broken, though.

**Pull request closed without merging**
